<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="30368" started-at="2018-08-14T06:52:39Z" finished-at="2018-08-14T06:53:09Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="30368" started-at="2018-08-14T06:52:39Z" finished-at="2018-08-14T06:53:09Z">
      <class name="Verify.Login">
        <test-method status="PASS" signature="ClientAdmin()[pri:0, instance:Verify.Login@8bd1b6a]" name="ClientAdmin" duration-ms="17998" started-at="2018-08-14T12:22:39Z" finished-at="2018-08-14T12:22:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ClientAdmin -->
        <test-method status="FAIL" signature="Manager()[pri:0, instance:Verify.Login@8bd1b6a]" name="Manager" duration-ms="12232" started-at="2018-08-14T12:22:57Z" finished-at="2018-08-14T12:23:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Title] but found [eDriver Client Application]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Title] but found [eDriver Client Application]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at Verify.Login.Manager(Login.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Manager -->
      </class> <!-- Verify.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
